default: &default
  adapter: postgresql
  database: <%= ENV.fetch('POSTGRES_DB', "test_rails_#{Rails.env}") %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  pool: <%= ENV.fetch('POSTGRES_DB_POOL', ENV.fetch('RAILS_MAX_THREADS', 5)) %>
  gssencmode: disable

development:
  primary:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB', 'test_rails_development') %>
  queue:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB', 'test_rails_development_queue') %>
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'test_rails_test') %>

production:
  <<: *default
